[build]
  publish = "client/build"
  command = "cd client && npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://your-railway-backend.railway.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
